'use client'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { ColorModeScript } from '@chakra-ui/react'
import { useState } from 'react'
import NavBar from '@/components/NavBar'
import DrawerNavBar from '@/components/Drawer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [open, setOpen] = useState(false)
  return (
    <html lang="en">
      <body>
        <ColorModeScript initialColorMode='dark' />
        <Providers>
          <NavBar setOpen={setOpen} />
          <DrawerNavBar setOpen={setOpen} open={open} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
